project:
  type: website ### this was changed (defaults to blog)
  output-dir: docs

website:
  site-url: "https://samridhi-singh-research.github.io/blog"
  title: "Your Blog Title"
  description: "A place for thinking out loud"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd